spring:
  application:
    name: kafka-tutorial
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

